### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "artistuser",
  "email": "artistuser@example.com",
  "password_hash": "password123",
  "role": "artist"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "artistuser@example.com",
  "password": "password123"
}

### Refresh Token
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Cookie: Refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzgzOTdlYzJiZTkyYzI1NjRmMjIzMGQiLCJpYXQiOjE3MzY2Nzc3MTUsImV4cCI6MTczNzI4MjUxNX0._Q_A_OcGTwvDPS3jY8TwX4BpNp_NZpL0K_hZFj96SwQ

### Get all users (requires JWT)
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzgzZDYxMzczY2YxOTU4MWMzMGIwMGYiLCJpYXQiOjE3MzY2OTMzNzQsImV4cCI6MTczNjY5Njk3NH0.p6w4I2qZ7sa3Wxq7KE6MOph1a91FZ9t8VLP2AEWI9eM

### Get user by ID (requires JWT)
GET http://localhost:3000/users/678397ec2be92c2564f2230d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzgzOTdlYzJiZTkyYzI1NjRmMjIzMGQiLCJpYXQiOjE3MzY2Nzc4MDQsImV4cCI6MTczNjY4MTQwNH0.owhfIoGfJyoIcVXvHIajyGg-69GzydVY2bbM4pLH8sk

### Update user by ID (requires JWT)
PATCH http://localhost:3000/users/6775b3c09f1135a6b9735899
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdkMzdhNjM0ZDkyMTA2ZmZmMjkxMTEiLCJpYXQiOjE3MzYyNjExOTEsImV4cCI6MTczNjI2NDc5MX0.moh5_uc5AH2yUSC6qBGUSi1pN1DCs8-8Z6qxDOI-BZc

{
  "username": "updateduser11",
  "email": "updateduser11@example.com"
}

### Delete user by ID (requires JWT)
DELETE http://localhost:3000/users/6775b3c09f1135a6b9735899
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdkMzdhNjM0ZDkyMTA2ZmZmMjkxMTEiLCJpYXQiOjE3MzYyNjExOTEsImV4cCI6MTczNjI2NDc5MX0.moh5_uc5AH2yUSC6qBGUSi1pN1DCs8-8Z6qxDOI-BZc











### Upload a new song
POST http://localhost:3000/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzgzZDYxMzczY2YxOTU4MWMzMGIwMGYiLCJpYXQiOjE3MzY2OTMzNzQsImV4cCI6MTczNjY5Njk3NH0.p6w4I2qZ7sa3Wxq7KE6MOph1a91FZ9t8VLP2AEWI9eM
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Test Song
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="duration"

300
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="trackNumber"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fileUrl"

http://localhost:3000/uploads/test-song.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="album"

ALBUM_ID
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="artist"

ARTIST_ID
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test-song.mp3"
Content-Type: audio/mpeg

< ./path/to/your/test-song.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--








### Upload a new song

POST http://localhost:3000/songs/upload
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzgzZDYxMzczY2YxOTU4MWMzMGIwMGYiLCJpYXQiOjE3MzY3MzM4MTYsImV4cCI6MTczNjczNzQxNn0.08PyL-zyclVNKuNTnO3iQw0EGGA9cbhwWFRkNFoL0Ls

{
  "title": "Test Song",
  "duration": 300,
  "trackNumber": 1,
  "fileUrl": "http://localhost:3000/uploads/test-song.mp3",
  "album": "ALBUM_ID",
  "artist": "ARTIST_ID"
}




### Upload a new song

POST http://localhost:3000/songs
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzgzZDYxMzczY2YxOTU4MWMzMGIwMGYiLCJpYXQiOjE3MzY3Mjc0MDYsImV4cCI6MTczNjczMTAwNn0._T21ZmaJ7ezm_Wv32ySOxbZaXSBRK5IPy5Td0AxjthQ

--boundary
Content-Disposition: form-data; name="title"
Test Song

--boundary
Content-Disposition: form-data; name="duration"
300

--boundary
Content-Disposition: form-data; name="trackNumber"
1

--boundary
Content-Disposition: form-data; name="file"; filename="test-song.mp3"
Content-Type: audio/mpeg

[Binary file data here]

--boundary--

















### Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "New Post",
  "contents": "This is the content of the new post",
  "userId": "67757a1915c5bfabeec231f7"
}

### Get all posts
GET http://localhost:3000/posts

### Get a post by ID
GET http://localhost:3000/posts/6775822d06140e6882d0119b

### Update a post
PATCH http://localhost:3000/posts/6775822d06140e6882d0119b
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post"
}

### Delete a post
DELETE http://localhost:3000/posts/677582cf06140e6882d0119f




### Create a new artist
POST http://localhost:3000/artists
Content-Type: application/json

{
  "name": "newartist",
  "bio": "This is a new artist.",
  "genre": "Rock"
}

### Get all artists
GET http://localhost:3000/artists

### Get an artist by ID
GET http://localhost:3000/artists/67839b181a2facbbdab5a46f

### Update an artist
PATCH http://localhost:3000/artists/6775b1e3a186aed400ae3ab2
Content-Type: application/json

{
  "name": "updatedartist",
  "bio": "This is an updated artist bio.",
  "genre": "Jazz"
}

### Delete an artist
DELETE http://localhost:3000/artists/6775b1e3a186aed400ae3ab2