### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "newuser11",
  "email": "newuser11@example.com",
  "password_hash": "password123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "newuser11@example.com",
  "password": "password123"
}

### Refresh Token
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Cookie: Refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdkMzdhNjM0ZDkyMTA2ZmZmMjkxMTEiLCJpYXQiOjE3MzYyNjEwNzksImV4cCI6MTczNjg2NTg3OX0.CbfPZVIO6gg4uxfBxEkNdBi5qw4vPIAN_y3O4Fy1IxU

### Get all users (requires JWT)
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdkMzdhNjM0ZDkyMTA2ZmZmMjkxMTEiLCJpYXQiOjE3MzYyNjExOTEsImV4cCI6MTczNjI2NDc5MX0.moh5_uc5AH2yUSC6qBGUSi1pN1DCs8-8Z6qxDOI-BZc

### Get user by ID (requires JWT)
GET http://localhost:3000/users/6775b3c09f1135a6b9735899
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdkMzdhNjM0ZDkyMTA2ZmZmMjkxMTEiLCJpYXQiOjE3MzYyNjExOTEsImV4cCI6MTczNjI2NDc5MX0.moh5_uc5AH2yUSC6qBGUSi1pN1DCs8-8Z6qxDOI-BZc

### Update user by ID (requires JWT)
PATCH http://localhost:3000/users/6775b3c09f1135a6b9735899
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdkMzdhNjM0ZDkyMTA2ZmZmMjkxMTEiLCJpYXQiOjE3MzYyNjExOTEsImV4cCI6MTczNjI2NDc5MX0.moh5_uc5AH2yUSC6qBGUSi1pN1DCs8-8Z6qxDOI-BZc

{
  "username": "updateduser11",
  "email": "updateduser11@example.com"
}

### Delete user by ID (requires JWT)
DELETE http://localhost:3000/users/6775b3c09f1135a6b9735899
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdkMzdhNjM0ZDkyMTA2ZmZmMjkxMTEiLCJpYXQiOjE3MzYyNjExOTEsImV4cCI6MTczNjI2NDc5MX0.moh5_uc5AH2yUSC6qBGUSi1pN1DCs8-8Z6qxDOI-BZc











### Upload a new song
POST http://localhost:3000/songs
Authorization: Bearer YOUR_JWT_TOKEN
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="title"

Test Song
--boundary
Content-Disposition: form-data; name="duration"

300
--boundary
Content-Disposition: form-data; name="trackNumber"

1
--boundary
Content-Disposition: form-data; name="fileUrl"

http://localhost:3000/uploads/test-song.mp3
--boundary
Content-Disposition: form-data; name="album"

ALBUM_ID
--boundary
Content-Disposition: form-data; name="artist"

ARTIST_ID
--boundary
Content-Disposition: form-data; name="file"; filename="test-song.mp3"
Content-Type: audio/mpeg

< ./path/to/your/test-song.mp3
--boundary--















### Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "New Post",
  "contents": "This is the content of the new post",
  "userId": "67757a1915c5bfabeec231f7"
}

### Get all posts
GET http://localhost:3000/posts

### Get a post by ID
GET http://localhost:3000/posts/6775822d06140e6882d0119b

### Update a post
PATCH http://localhost:3000/posts/6775822d06140e6882d0119b
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post"
}

### Delete a post
DELETE http://localhost:3000/posts/677582cf06140e6882d0119f




### Create a new artist
POST http://localhost:3000/artists
Content-Type: application/json

{
  "name": "newartist",
  "bio": "This is a new artist.",
  "genre": "Rock"
}

### Get all artists
GET http://localhost:3000/artists

### Get an artist by ID
GET http://localhost:3000/artists/6775b1e3a186aed400ae3ab2

### Update an artist
PATCH http://localhost:3000/artists/6775b1e3a186aed400ae3ab2
Content-Type: application/json

{
  "name": "updatedartist",
  "bio": "This is an updated artist bio.",
  "genre": "Jazz"
}

### Delete an artist
DELETE http://localhost:3000/artists/6775b1e3a186aed400ae3ab2