### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "newuser11",
  "email": "newus21@example.com",
  "password_hash": "password123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "newuser10",
  "password": "password123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "newus21@example.com",
  "password": "password123"
}

### Get all users
GET http://localhost:3000/users

### Get a user by ID
GET http://localhost:3000/users/6775dcfe901bac204899d7ca

### Update a user
PATCH http://localhost:3000/users/6775dcfe901bac204899d7ca
Content-Type: application/json

{
  "username": "updateduser",
  "email": "updateduse@example.com",
  "password_hash": "newpassword123"
}

### Delete a user
DELETE http://localhost:3000/users/677531fcbcacbfa59f293a5f

### Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "New Post",
  "contents": "This is the content of the new post",
  "userId": "67757a1915c5bfabeec231f7"
}

### Get all posts
GET http://localhost:3000/posts

### Get a post by ID
GET http://localhost:3000/posts/6775822d06140e6882d0119b

### Update a post
PATCH http://localhost:3000/posts/6775822d06140e6882d0119b
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post"
}

### Delete a post
DELETE http://localhost:3000/posts/677582cf06140e6882d0119f




### Create a new artist
POST http://localhost:3000/artists
Content-Type: application/json

{
  "name": "newartist",
  "bio": "This is a new artist.",
  "genre": "Rock"
}

### Get all artists
GET http://localhost:3000/artists

### Get an artist by ID
GET http://localhost:3000/artists/6775b1e3a186aed400ae3ab2

### Update an artist
PATCH http://localhost:3000/artists/6775b1e3a186aed400ae3ab2
Content-Type: application/json

{
  "name": "updatedartist",
  "bio": "This is an updated artist bio.",
  "genre": "Jazz"
}

### Delete an artist
DELETE http://localhost:3000/artists/6775b1e3a186aed400ae3ab2